import { Property } from "./property";
import { Review } from "./review";

export const PROPERTIES: Property[] = [
    { name: 'Maplewood Heights Apartments', 
    description: 'Maplewood Heights Apartments is a luxury apartment complex nestled in the heart of a bustling downtown area. The complex boasts modern amenities such as a fitness center, rooftop pool, and 24-hour concierge service. The units are spacious and feature high-end finishes, stainless steel appliances, and breathtaking views of the city skyline.', 
    monthlyRent: 3500, address: '1234 Maple Street, Suite 567, Fargo, USA', sqFootage: 1200, numBeds: '2', numBaths: '2', 
    depositAmount: 5500, rentLength: '6 month lease', petPolicy: 'Allowed', 
    reviews: [{reviewerName: 'Matthew Parker', rating: 4.5,
    reviewText: 'I recently stayed at Maplewood Heights and it was an absolute delight. The apartment was spacious, modern and impeccably clean. The location was also fantastic, with easy access to public transportation and great restaurants nearby. The amenities provided were top-notch, from the fitness center to the pool. The staff was friendly, accommodating and always available to help with any needs. Overall, I highly recommend Maplewood Heights for anyone looking for a comfortable and convenient stay in the city.'}, 
    {reviewerName: 'Lara Stevens', rating: 3,
    reviewText: 'I recently stayed at Maplewood Heights and overall, I had a decent experience. The apartment was clean and had all the necessary amenities, although some of the furniture seemed a bit worn out. The location was convenient and close to public transportation, but the area felt a bit noisy at times. The staff was friendly and helpful when needed, but there were a few minor issues with communication. Overall, I had a moderately satisfying stay at Maplewood Heights and would recommend it for someone looking for a decent, no-frills apartment in the city.'},
    {reviewerName: 'Shawn Roth', rating: 1,
    reviewText: 'I had an absolutely terrible experience staying at Maplewood Heights. The apartment was dirty and in poor condition, with broken appliances and outdated furniture. The location was not convenient and felt unsafe at night. The staff was unprofessional and unhelpful, and I had several issues with them not addressing my concerns in a timely or satisfactory manner. Additionally, the amenities were lacking and not as advertised. I would not recommend Maplewood Heights to anyone and advise against staying there.'},
    ] },
    
    { name: 'Park View Residences',
    description: 'Park View Residences offers luxurious, modern living in the heart of the city. The spacious apartments feature high-end finishes, stainless steel appliances, and stunning city views. Building amenities include a fitness center, rooftop pool, and 24-hour concierge service.',
    monthlyRent: 3400, address: '4321 Main St, Suite 234, Fargo, USA', sqFootage: 1100, numBeds: '2', numBaths: '2', 
    depositAmount: 5000, rentLength: '12 month lease', petPolicy: 'Pets are welcome with an additional monthly fee of $50 per pet. Some breed and weight restrictions may apply.', 
    reviews: [{reviewerName: 'Tod Werner', rating: 5,
    reviewText: 'I had an amazing experience staying at Park View Residences! The apartment was spacious, beautifully decorated, and had all the amenities I needed. The location was perfect, with plenty of restaurants and shops nearby. The staff was friendly and always willing to help with any questions or concerns I had. The rooftop pool and fitness center were also a great bonus. Overall, I highly recommend Park View Residences to anyone looking for a luxurious and convenient place to stay in the city.'}, 
    {reviewerName: 'Greg Garner', rating: 4,
    reviewText: 'I had a good experience staying at Park View Residences. The apartment was spacious and had all the modern amenities, but some of the finishes felt a bit worn out. The location was great, with easy access to public transportation and nearby restaurants. The staff was friendly and helpful, although there were a few minor issues with communication. The rooftop pool and fitness center were a great way to unwind after a long day. Overall, I would recommend Park View Residences to anyone looking for a comfortable and convenient stay in the city.'},
    {reviewerName: 'Ray Mccall', rating: 3,
    reviewText: 'My stay at Park View Residences was average. The apartment was clean and had all the necessary amenities, but some of the appliances were outdated and in need of repair. The location was convenient, but the area felt a bit noisy at times. The staff was helpful, but there were a few issues with communication and responsiveness. The rooftop pool and fitness center were nice, but felt overcrowded at times. Overall, I had a decent experience at Park View Residences, but there is definitely room for improvement.'},
    ] },

    { name: 'Hillcrest Apartments',
    description: 'Hillcrest Apartments offers affordable and comfortable living in a convenient location. The apartments feature basic finishes and appliances, but provide all the necessary amenities for everyday living. Building amenities include a fitness center and laundry facilities.',
    monthlyRent: 1200, address: '5678 Oak St, Suite, Fargo, USA', sqFootage: 800, numBeds: '1', numBaths: '1',
    depositAmount: 1200, rentLength: '6 or 12 month lease', petPolicy: 'Cats and small dogs are welcome with an additional monthly fee of $25 per pet. Some breed and weight restrictions may apply.',
    reviews: [{reviewerName: 'Alissa Wright', rating: 4,
    reviewText: 'Hillcrest Apartments provided me with a comfortable and affordable place to stay. The apartment was clean and had all the necessary amenities, although some of the finishes were a bit outdated. The location was convenient, with easy access to public transportation and nearby shops. The staff was friendly and always willing to help with any issues. The fitness center and laundry facilities were a great bonus. Overall, I would recommend Hillcrest Apartments to anyone looking for an affordable and convenient place to live.'},
    {reviewerName: 'Annette Gilmore', rating: 3, 
    reviewText: 'My experience at Hillcrest Apartments was average. The apartment was clean and functional, but lacked some of the modern amenities I was used to. The location was convenient, but the area felt a bit noisy at times. The staff was friendly, but there were some issues with maintenance and responsiveness. The fitness center and laundry facilities were helpful, but could get crowded at peak times. Overall, Hillcrest Apartments provided me with a basic and affordable place to stay, but there is definitely room for improvement.'},
    {reviewerName: 'Steve Rice', rating: 2,
    reviewText: 'I had a disappointing experience staying at Hillcrest Apartments. The apartment was outdated and in need of repairs, with appliances that didn\'t work properly. The location was convenient, but the area felt unsafe at times. The staff was unresponsive and unhelpful, and I had several issues with maintenance not being addressed in a timely manner. The fitness center and laundry facilities were basic and often overcrowded. Overall, I would not recommend Hillcrest Apartments to anyone looking for a comfortable and convenient place to live.'},
    ] },

    { name: 'Shady Grove Apartments', 
    description: 'Shady Grove Apartments offers low-cost living in a less desirable location. The apartments are old and in poor condition, with outdated appliances and worn-out finishes. Building amenities are minimal and may not be properly maintained.', 
    monthlyRent: 800, address: '9012 Elm St, Fargo, USA', sqFootage: 600, numBeds: 'Studio', numBaths: '1',
    depositAmount: 500, rentLength: 'Month-to-month lease', petPolicy: 'No pets allowed.',
    reviews: [{reviewerName: 'Nola Adams', rating: 1,
    reviewText: 'I had a terrible experience living at Shady Grove Apartments. The apartment was old, dingy, and in poor condition. The appliances were outdated and barely worked. The building itself was poorly maintained and had a strange smell. The location was inconvenient and unsafe, with a lot of noise and disturbances at all hours. The lack of proper amenities and management made my experience even worse. Overall, I would not recommend Shady Grove Apartments to anyone looking for a decent place to live.'},
    {reviewerName: 'Betsy Cohen', rating: 2,
    reviewText: 'My experience at Shady Grove Apartments was below average. The apartment was small and outdated, but manageable. The location was inconvenient and not very safe. The lack of amenities and proper maintenance made it difficult to live comfortably. The management was unresponsive and didn\'t seem to care about our concerns. Overall, I would not recommend Shady Grove Apartments to anyone looking for a decent place to live.'},
    {reviewerName: 'Mitchel Norris', rating: 2,
    reviewText: 'Shady Grove Apartments was a disappointing place to live. The apartment was old and in need of repairs, with appliances that barely worked. The location was far from everything and didn\'t feel very safe. The lack of amenities and proper maintenance made it difficult to live comfortably. The management was unresponsive and unhelpful. Overall, I would not recommend Shady Grove Apartments to anyone looking for a comfortable and convenient place to live.'},
    ] },
];
